# Generated by Django 5.1.5 on 2026-02-16 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('artist', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='song_author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='song_title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='song_url',
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='diary.song'),
        ),
    ]
