# Generated by Django 5.1.5 on 2026-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_song_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
